spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/event-db
    username: login
    password: pass

server:
  port: 0

grpc:
  client:
    analyzer-client: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///analyzer' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector-client: # <- должно соответствовать значению в @GrpcClient
      address: 'static://localhost:8086' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.practicum.event: DEBUG
    ru.practicum.explorewithme.client: DEBUG