services:
  ewm-service:
    build: main-service
    image: explore-with-me-main-service
    container_name: explore-with-me-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - main-service-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-service-db:5432/mainservicedb
      - SPRING_DATASOURCE_USERNAME=mainservice
      - SPRING_DATASOURCE_PASSWORD=mainservice
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  stats-server:
    build: stat/stat-server
    image: explore-with-me-stat-server
    container_name: explore-with-me-stat-server
    ports:
      - "9090:9090"
    depends_on:
      stat-server-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-server-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  main-service-db:
    image: postgres:16.1
    container_name: postgres-main-service
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=mainservice
      - POSTGRES_USER=mainservice
      - POSTGRES_DB=mainservicedb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  stat-server-db:
    image: postgres:16.1
    container_name: postgres-stat-server
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
