services:
  event-service-db:
    image: postgres:16.1
    container_name: postgres-event-service
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=login
      - POSTGRES_DB=event-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  stat-server-db:
    image: postgres:16.1
    container_name: postgres-stat-server
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  user-service-db:
    image: postgres:16.1
    container_name: postgres-user-service
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=login
      - POSTGRES_DB=user-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  request-service-db:
    image: postgres:16.1
    container_name: postgres-request-service
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=login
      - POSTGRES_DB=request-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  comment-service-db:
    image: postgres:16.1
    container_name: postgres-comment-service
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=login
      - POSTGRES_DB=comment-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  analyzer-db:
    image: postgres:16.1
    container_name: postgres-analyser-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=db-user
      - POSTGRES_DB=analyzer
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"