spring:
  application:
    name: stat-server
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/statdb
    username: stat
    password: stat

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/